project:
    artifactId: book
    name: book
    version: 1.0
    description: Demo project for info endpoint
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: kenyahighcom@gmail.com
    password: khc_2030
    port: 587
    properties:
      mail:
        debug : true
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
# For Spring Actuator /info endpoint
info:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

eureka:
  instance:
    # interval for periodic heartbeat to the registry; default 10
    leaseRenewalIntervalInSeconds: 10
  client:
    enabled: true
    registryFetchIntervalSeconds: 5
    # by default, Eureka uses the client heartbeat to determine if a client is up. Unless specified otherwise the
    # Discovery Client will not propagate the current health check status of the application.
    # should only be set in application.yml
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_ZONE}

# use a HTTP port 8080
server:
  port: 8080